# This workflow will do a clean installation of dependencies, run test coverage and send the coverage report to Coveralls.
# This workflow currently allows code coverage reporting on Coveralls even if some tests fail.
# To change the workflow to not send Coverage reports when tests fail, simply remove the line "continue_on_error: true".

name: Test Coverage CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}

    strategy:
      matrix:
        node-version: [16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run tests with coverage
        continue-on-error: true
        run: npm run coverage

      - name: Send coverage data to Coveralls
        if: always()
        run: npx coveralls < ./coverage/lcov.info
